<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2020 pig4cloud Authors. All Rights Reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.ynlk4cloud</groupId>
		<artifactId>ynlk</artifactId>
		<version>1.0.0</version>
	</parent>
	<groupId>com.ynlk4cloud</groupId>
	<artifactId>ynlk-common</artifactId>
	<packaging>pom</packaging>

	<description>公共聚合模块</description>

	<modules>
		<module>ynlk-common-core</module>
		<module>ynlk-common-datasource</module>
		<module>ynlk-common-job</module>
		<module>ynlk-common-log</module>
		<module>ynlk-common-mybatis</module>
		<module>ynlk-common-security</module>
		<module>ynlk-common-feign</module>
		<module>ynlk-common-swagger</module>
		<module>ynlk-common-test</module>
		<module>ynlk-common-mq</module>
		<module>ynlk-common-seata</module>
	</modules>
</project>
