<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.ynlk4cloud</groupId>
		<artifactId>ynlk</artifactId>
		<version>1.0.0</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.ynlk4cloud</groupId>
	<artifactId>ynlk-dc</artifactId>
	<packaging>pom</packaging>
	<version>1.0.0</version>
	<!--<version>3.2.2</version>-->
	<name>ynlk-dc</name>
	<description>数据中台</description>

	<modules>
		<module>ynlk-dc-api</module>
		<module>ynlk-dc-biz</module>
	</modules>

</project>
